import pytest
import json

@pytest.fixture(autouse=True)
def skip_on_live(is_live_editor):
    if is_live_editor:
        pytest.skip("Skipping mock-only tests on live editor.")

def test_get_blueprint_schema_invalid_param_types(mock_agent_client):
    """
    Stress test get_blueprint_schema with invalid parameter types (e.g., dict, list, int instead of string).
    """
    # Test with asset_path as a dictionary
    res = mock_agent_client.call_cpp_tool(
        'get_blueprint_schema',
        {'asset_path': {'invalid': 'type'}}
    )
    assert res is not None
    assert res.get('bSuccess') is False

    # Test with asset_path as an integer
    res = mock_agent_client.call_cpp_tool(
        'get_blueprint_schema',
        {'asset_path': 12345}
    )
    assert res is not None
    assert res.get('bSuccess') is False

def test_get_blueprint_schema_malformed_paths(mock_agent_client):
    """
    Stress test get_blueprint_schema with malformed package paths.
    """
    # Path not starting with /Game/
    res = mock_agent_client.call_cpp_tool(
        'get_blueprint_schema',
        {'asset_path': '/Engine/BasicShapes/Cube'}
    )
    assert res is not None
    assert res.get('bSuccess') is False

    # Path containing invalid character (e.g., spaces or backslashes)
    res = mock_agent_client.call_cpp_tool(
        'get_blueprint_schema',
        {'asset_path': '/Game/Blueprints/My Character Name'}
    )
    assert res is not None
    assert res.get('bSuccess') is False

    # Path ending with a slash
    res = mock_agent_client.call_cpp_tool(
        'get_blueprint_schema',
        {'asset_path': '/Game/Blueprints/'}
    )
    assert res is not None
    assert res.get('bSuccess') is False

def test_get_blueprint_schema_non_blueprint_assets(mock_agent_client):
    """
    Stress test get_blueprint_schema with non-blueprint assets (e.g. static mesh or material).
    """
    # Material path
    res = mock_agent_client.call_cpp_tool(
        'get_blueprint_schema',
        {'asset_path': '/Game/Low_Poly_Sci-Fi_Corridor/Materials/M_Corridor_01_A_NonBlueprintAsset'}
    )
    assert res is not None
    assert res.get('bSuccess') is False
    errors = res.get('Errors', [])
    assert any("not a blueprint" in err.lower() or "failed to load" in err.lower() for err in errors)

def test_get_blueprint_schema_subclasses_and_types(mock_agent_client):
    """
    Test schema extraction compatibility across subclasses (UserWidget, AnimInstance) and complex types.
    """
    # Anim Blueprint
    res = mock_agent_client.call_cpp_tool(
        'get_blueprint_schema',
        {'asset_path': '/Game/Animations/ABP_Mannequin'}
    )
    assert res is not None
    assert res.get('bSuccess') is True
    schema = json.loads(res.get('ResultMessage', '{}'))
    assert schema.get("parent_class") == "AnimInstance"

    # Widget Blueprint
    res = mock_agent_client.call_cpp_tool(
        'get_blueprint_schema',
        {'asset_path': '/Game/UI/WBP_MainMenu'}
    )
    assert res is not None
    assert res.get('bSuccess') is True
    schema = json.loads(res.get('ResultMessage', '{}'))
    assert schema.get("parent_class") == "UserWidget"

def test_get_blueprint_schema_container_types(mock_agent_client):
    """
    Stress test with container types to make sure they are extracted as expected.
    """
    res = mock_agent_client.call_cpp_tool(
        'get_blueprint_schema',
        {'asset_path': '/Game/Blueprints/BP_ContainerTest'}
    )
    assert res is not None
    assert res.get('bSuccess') is True
    schema = json.loads(res.get('ResultMessage', '{}'))
    variables = schema.get("variables", [])
    
    var_types = {v["name"]: v["type"] for v in variables}
    assert "TArray<float>" in var_types.get("MyArray", "")
    assert "TSet<FString>" in var_types.get("MySet", "")
    assert "TMap<FString, int32>" in var_types.get("MyMap", "")

def test_add_blueprint_variable_roundtrip_compatibility(mock_agent_client):
    """
    Adversarial verification of the type round-trip compatibility.
    Exposes the bug where types generated by get_blueprint_schema (like TArray<float>)
    cannot be resolved by add_blueprint_variable (resolving to wildcard instead).
    """
    # 1. Retrieve the schema of BP_ContainerTest to get the type of 'MyArray'
    res = mock_agent_client.call_cpp_tool(
        'get_blueprint_schema',
        {'asset_path': '/Game/Blueprints/BP_ContainerTest'}
    )
    assert res is not None
    assert res.get('bSuccess') is True
    schema = json.loads(res.get('ResultMessage', '{}'))
    
    variables = schema.get("variables", [])
    my_array_var = next((v for v in variables if v["name"] == "MyArray"), None)
    assert my_array_var is not None
    extracted_type = my_array_var["type"] # e.g. "TArray<float>"
    
    # 2. Attempt to call add_blueprint_variable using the extracted type.
    res_add = mock_agent_client.call_cpp_tool(
        'add_blueprint_variable',
        {
            'asset_path': '/Game/Blueprints/BP_ContainerTest',
            'variable_name': 'NewRoundtripVar',
            'variable_type': extracted_type
        }
    )
    assert res_add is not None
    assert res_add.get('bSuccess') is True, f"Failed to add variable: {res_add.get('Errors')}"

    # 3. Perform a subsequent get_blueprint_schema call
    res_subsequent = mock_agent_client.call_cpp_tool(
        'get_blueprint_schema',
        {'asset_path': '/Game/Blueprints/BP_ContainerTest'}
    )
    assert res_subsequent is not None
    assert res_subsequent.get('bSuccess') is True
    subsequent_schema = json.loads(res_subsequent.get('ResultMessage', '{}'))
    subsequent_vars = subsequent_schema.get("variables", [])

    # 4. Find the new variable and assert its type matches extracted_type exactly
    new_var = next((v for v in subsequent_vars if v["name"] == "NewRoundtripVar"), None)
    assert new_var is not None, "NewRoundtripVar was not found in the blueprint schema after creation."
    assert new_var["type"] == extracted_type, f"Variable type mismatch: expected '{extracted_type}', got '{new_var['type']}' (fallback to wildcard?)"
