$PSScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$PluginDir = (Resolve-Path (Join-Path $PSScriptDir "..")).Path

# Try to find the uproject file dynamically by searching upwards
$ProjectRoot = $PluginDir
$UprojectFile = $null
for ($i = 0; $i -lt 5; $i++) {
    $Files = Get-ChildItem -Path $ProjectRoot -Filter *.uproject -ErrorAction SilentlyContinue
    if ($Files) {
        $UprojectFile = $Files[0].FullName
        break
    }
    $ProjectRoot = Split-Path -Parent $ProjectRoot
}

if (-not $UprojectFile) {
    # Default fallback if no project file is found
    $ProjectRoot = (Resolve-Path (Join-Path $PluginDir "../../..")).Path
    $UprojectFile = Join-Path $ProjectRoot "Tau.uproject"
}

$RegistryPath = "HKLM:\SOFTWARE\EpicGames\Unreal Engine\5.7"
$InstalledDir = (Get-ItemProperty -Path $RegistryPath -Name InstalledDirectory -ErrorAction SilentlyContinue).InstalledDirectory
if (-not $InstalledDir) {
    $InstalledDir = "C:\Program Files\Epic Games\UE_5.7"
}
$EditorExe = Join-Path $InstalledDir "Engine\Binaries\Win64\UnrealEditor.exe"
$BuildTool = Join-Path $InstalledDir "Engine\Build\BatchFiles\Build.bat"
$ProjectFile = $UprojectFile
$DevAuthTool = "C:\Program Files\EOS_DevAuthTool\EOS_DevAuthTool.exe"

$UnrealEnvSkillDir = Join-Path $PluginDir "skills\unreal-env"
if (-not (Test-Path $UnrealEnvSkillDir)) {
    New-Item -ItemType Directory -Force -Path $UnrealEnvSkillDir | Out-Null
}

$SkillContent = @"
---
name: unreal-env
description: Dynamic local environment configuration for Unreal Engine development, including machine-specific paths and commands to build and run the project.
---
# Unreal Local Environment Configuration

This skill is dynamically generated by the environment setup script and contains machine-specific paths and commands for building and running the Unreal Engine project on this machine.

## Local Paths

- **Unreal Engine Root:** $InstalledDir
- **Unreal Editor Executable:** $EditorExe
- **Unreal Build Tool:** $BuildTool
- **Unreal Project File:** $ProjectFile
- **EOS DevAuthTool:** $DevAuthTool

## Developer Tool Workflows

### 1. EOS DevAuthTool
When authentication is required (e.g. for PvP matchmaking or testing round startup), start this tool first:
```powershell
Start-Process -FilePath "$DevAuthTool"
```
Wait until the user has interacted with the opened EOS_DevAuthTool window (e.g. to log in, accept scopes, or configure credentials) before trying to use it for authentication.

### 2. Building the Project
To compile the C++ code and binaries for the editor (e.g. when editor is closed, to prevent out-of-date binaries preventing launch):
```powershell
Start-Process -FilePath "$BuildTool" -ArgumentList "TauEditor", "Win64", "Development", '"$ProjectFile"', "-WaitMutex" -Wait -NoNewWindow
```

### 3. Launching the Unreal Editor
To launch the Unreal Editor with the project and developer authentication arguments:
```powershell
cmd.exe /c '""$EditorExe" "$ProjectFile" -CustomConfig=EOS -AUTH_TYPE=developer -AUTH_LOGIN=localhost:8080 -AUTH_PASSWORD=TauDev"'
```

"@

Set-Content -Path (Join-Path $UnrealEnvSkillDir "SKILL.md") -Value $SkillContent
Write-Host "Generated dynamic unreal-env skill at $(Join-Path $UnrealEnvSkillDir 'SKILL.md')"
